# Generated by Django 4.2.7 on 2023-11-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='objects',
            new_name='object',
        ),
    ]
