# Generated by Django 4.2.7 on 2024-03-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_rename_objects_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='heading',
            field=models.CharField(max_length=200),
        ),
    ]
